scan_topic: "base_scan"


odom_topic: "odom"

base_link_topic : "base_link"

gt_pose_topic: "base_pose_ground_truth"

goal_seeker: "goal_seeker"

goal_seeker_drive_topic: "cmd_vel"
threshold_for_triggering_ransac: 2.0

inliner_threshold: 0.1

ransac_iteration_count : 5
goal_pt: [4.5,9.0]
start_pt: [-8.0,-2.0]

ransac_lines : "obstacle_lines"
drive_line : "drive_direction"

collision_threshold: 0.7
collision_detection_threshold: 0.6
wall_follow_dist: 0.6

kp: 1.6
ki: 0.05
kd: 0.1
look_ahead : 0.9